In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))

In [3]:
randint

tensor([-18, -92,  24,  70, -95, -92])

In [4]:
tensor = torch.tensor([[0.1,0.2],[2.2,3.1],[4.5,5.4]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.5000, 5.4000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [13]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])